### ISSUE TITLE
Unable to call URL

### ISSUE THREAD

**Issue by Seireinosenshi** [anderson-university/workday-profile-image-collector#1]
When running the python script hitting a weird problem, the logs stat "ERROR: Employee Photos - GET photo data failed -", i have looked over the links and all seems correct and even see it logging into the Workday Testing tenant. Any thoughts on what may i be missing here ?

**Comment by espressoj** [comment]
The code should provide more detail after the dash in "ERROR: Employee Photos - GET photo data failed - ". Is there additional information that you can share?

**Comment by Seireinosenshi** [comment]
ERROR: Employee Photos - GET photo data failed - Expecting value: line 1 column 1 (char 0), I double checked the report and made sure everything was in the correct lines, the one question if have is the "Active Status", wasn't able to find this field within the tenant and assume its a calc field.

**Comment by espressoj** [comment]
Active Status is a Workday delivered field on the Worker business object.  

**Field Name:** Active Status 
**Description:** Returns 'Yes' if the worker is active as of the report date if provided; excludes workers who are on certain types of leave or who are terminated.
**Field Source:** Workday Delivered 
**Field Type:** Boolean
**Related Business Object:**
**Built-in Prompts:** Report Writer Provided Top Level Effective Moment 
**Category:** Job & Position
**Authorized Usage:** Security Attribute - System User

Can you reach out to your designated Wd security admin and have them double-check to make sure the account you are using has the necessary permissions?

**Comment by Seireinosenshi** [comment]
Gained access to that field and fixed the reports, running into these errors.

"https://wd2-impl-services1.workday.com/ccx/service/customreport2/TenantName/Username@/CR_Employees_Profile_Photos_with_Base64_Image_Data?Worker%21Employee_ID=XXXXX
Traceback (most recent call last):
  File "/root/workday-profile-image-collector/Workday_Employees-Photo-Export.py", line 116, in <module>
    main()
  File "/root/workday-profile-image-collector/Workday_Employees-Photo-Export.py", line 111, in main
    process_url(empIDs)
  File "/root/workday-profile-image-collector/Workday_Employees-Photo-Export.py", line 79, in process_url
    for employee in data_emp_photos['Report_Entry']:
UnboundLocalError: local variable 'data_emp_photos' referenced before assignment

Error log shows "ERROR: Employee Photos - GET photo data failed - Expecting value: line 1 column 1 (char 0)"

**Comment by espressoj** [comment]
I updated the python code to include additional exception handling and added a conditional to make sure that Employee IDs were returned in the first report before attempting to process the second. The updates have been pushed to GitHub.  Copy your local variables in the ########## block and use the new code.

**Comment by Seireinosenshi** [comment]
All copied, this has gotten us much farther but hitting this error now:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/PIL/Image.py", line 2415, in save
    format = EXTENSION[ext]
KeyError: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/workday-profile-image-collector/Workday_Employees-Photo-Export.py", line 141, in <module>
    main()
  File "/root/workday-profile-image-collector/Workday_Employees-Photo-Export.py", line 136, in main
    process_url(empIDs)
  File "/root/workday-profile-image-collector/Workday_Employees-Photo-Export.py", line 100, in process_url
    image.save("{PATH_TO_LOCAL_STORAGE_FOLDER_FOR_IMAGE_FILES}\{employee_id}{IMAGE_FILE_FORMAT}")
  File "/usr/local/lib/python3.9/dist-packages/PIL/Image.py", line 2418, in save
    raise ValueError(msg) from e
ValueError: unknown file extension:

**Comment by espressoj** [comment]
In the variables section, make sure that IMAGE_FILE_FORMAT = one of the following:
".jpg", ".png", ".gif", ".bmp", ".tiff", ".tif", ".ico", ".webp", ".ppm", ".pgm", ".jp2"

Be sure to include the "." before the extension type.

**Comment by Seireinosenshi** [comment]
<img width="540" alt="Screenshot 2023-12-12 at 9 07 49 AM" src="https://github.com/anderson-university/workday-profile-image-collector/assets/50635687/1263878b-8a69-42f9-8ba6-a66b2384840d">
The variable is set, tried different ones but still the same error.

**Comment by espressoj** [comment]
It may be that an employee is missing an Employee ID.  I have pushed an update that handles a missing ID, logging the issue along with the worker name, and moving on to the next record. If an ID is missing, it will attempt to save the file as \\Path\\To\\File\\.jpg and fail.  You can also define a file name in the "else:" clause, adding another unique value for the record.

**Comment by espressoj** [comment]
Seireinosenshi, did my last response solve the issue you were having?
